//TABLES
export const TABLES_GET_SUCCESS = "TABLES_GET_SUCCESS";
export const TABLES_POST_SUCCESS = "TABLES_POST_SUCCESS";
export const TABLE_ASSIGN_SUCCESS = "TABLE_ASSIGN_SUCCESS";

//USERS
export const USERS_GET_SUCCESS = "USERS_GET_SUCCESS";
export const USERS_POST_SUCCESS = "USERS_POST_SUCCESS";
